### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by VeitSanner** [p-e-w/language-javascript-semantic#13] opened 2015-02-21 12:10 UTC
The atom.syntax global is deprecated. Use atom.grammars instead.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:320:11)
Object.activate (/Users/vsanner/.atom/packages/language-javascript-semantic/lib/main.coffee:13:9)
```

**Comment by p-e-w** [comment] 2015-03-02 17:50
**Exact** duplicate of https://github.com/p-e-w/language-javascript-semantic/issues/11. Was this reported using a deprecation auto-detect script of some kind?

**Closed by p-e-w** 2015-03-02 17:50 UTC
Labels: duplicate

**Comment by Duder-onomy** [comment] 2015-03-02 18:15
When we all upgraded to the latest ATOM, we got this fancy alert at the bottom of the screen: 
![image](https://cloud.githubusercontent.com/assets/1612785/6447125/c6c0e068-c0c4-11e4-92ff-19b640447f65.png)

It tells us which packages are using deprecated methods: 
![image](https://cloud.githubusercontent.com/assets/1612785/6447144/df3d8f10-c0c4-11e4-9001-ca80d8cd2d02.png)

When you expand the above, It gives you an option to auto open an issue on github: 
![image](https://cloud.githubusercontent.com/assets/1612785/6447155/f5f1a610-c0c4-11e4-95fa-b53cb9f8d34f.png)

I think you should take these duplicate issues as a compliment on how important/useful people find this in their everyday work.

**Comment by p-e-w** [comment] 2015-03-02 18:27
That's a pretty cool and sensible feature, didn't know about it :smile:
